name: Docker Image CI

on:
  workflow_dispatch:

  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:    
    - uses: actions/checkout@v4    

    - name: Docker Login
      uses: docker/login-action@v3.3.0
      with:
        registry: ghcr.io
        username: bognarpal
        password: ${{secrets.GHCR_TOKEN}}      
    
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ghcr.io/bognarpal/joke-client:0.2                
        docker push ghcr.io/bognarpal/joke-client:0.2
